### ISSUE TITLE
Add support for Hugo

### ISSUE THREAD

**Issue by lislis** [ffalt/hookay#3]
Hey @ffalt!
I'd like to add build support for [Hugo](https://gohugo.io/) to hookay.

The webhook flow would be the same as for Jekyll, except that it would run `$ hugo` and then move the generated `public/` directory to the specified dest_path.

I would check in a Hugo binary that does all the building, there are no further dependencies needed.

What do you think? Do you think it's feasible? I guess `lib/executor.js` would be a good start point but creating a different Task for Hugo?

**Comment by ffalt** [comment]
Hi! I just took a look, ohmy, that code aged fast...

Yes, lib/executer.js is right. Instead of calling runJekyll(), a runHugo() function could be easily conditionally called with a new config (task) option. But I'm not sure about the binary (to have hookay as platform independend as possible).

runJekyll() installs a jekyll builder version specified in the project for each project. I'm not too familiar with hugo, maybe it is more version agnostic than jekyll. I still think it's better to adapt that for hugo too, if possible.

- getGit() // clone/update the git project into a temp folder $project/build
- runHugo() {
  - run a hugo install if needed, eg. https://github.com/dominique-mueller/hugo-installer
   download into a subfolder like $project/hugo
  - run _$project/hugo_/hugo(.exe) to build the static site into $project/build/_site
}
- publishSite() // copy $project/build/_site into publish folder

Let me know where I can help!

**Comment by lislis** [comment]
Thank you for the quick feedback and digging up hugo-installer!
I'll try and and open a PR with some suggestions by tomorrow

**Comment by lislis** [comment]
Hey again, I opened #4 as a first step. Now trying to get a second hookay instance running for testing this

**Comment by ffalt** [comment]
hi! last weekend I created a deploy library, mostly for my angular & npm projects, but added hugo/jekyll, too. my plan is to use that https://github.com/ffalt/deplokay in hookay (75% done). hookay will be just the hook-listener and the web frontend. unfortunately, then your efforts will be removed. I'm very sorry for not informing and warning you :/ I'm travelling until friday, then I'll continue...

**Comment by lislis** [comment]
@ffalt hey there! I just took a look at the new hookay version and deplokay. Very sweet! I'll to upgrade the okf hookay with our admin this week (:crossed_fingers:) and then close this ticket.
Thank you for all the work!

**Comment by ffalt** [comment]
:)

one important hint for upgrading. 
before, the main branch of this repository could be used as is (and so it is on the okf server). now, with transpiling, the main branch contains only the source. So you must switch to the [releases branch](https://github.com/ffalt/hookay/tree/releases) to use the repository directly - or, not recommended, download a [zip release](https://github.com/ffalt/hookay/releases .
I changed a typo in the old config file format ("repro"), so hookay should complain about deprecation, but read it anyway.
Let me know, if you find any bugs or hickups.

**Comment by lislis** [comment]
Hey again @ffalt !
We just updated the version and everything runs smoothly with the old config version file.

When we started updating the config.json to change `repro` to `repository` we then get this error whn trying to start it with forever:

```
DEPRECATION WARNING: You are using the old config format, please update your settings
Reading Config: okfn.de/master
Missing Option "source.remote.repository": Please provide a git repository
error: Forever detected script exited with code: 0
```

The error comes from deplokay but I'm not sure why it's happening? We configured `repository` so that should work I guess? Any hints?

**Comment by ffalt** [comment]
ah I see, you must follow the full new spec if you want to upgrade to the new format. sorry, forgot to document that. I introduced a version attribute to the config format. Please add "version": 2 to your config file, also the new "build":"jekyll" or "build":"hugo" property for each site.

**Comment by ffalt** [comment]
does it work? the okf hookay is not found on the url I know, but maybe you moved it.

**Comment by lislis** [comment]
Ah, I didn't have time yet to update the config yesterday. I'll have another look next week :)

> okf hookay

You mean for the live version? That should still be reachable under the old url but redirecting to /build-status

**Comment by lislis** [comment]
Update: apparently there was a mistake in the redirect, should work now

**Comment by ffalt** [comment]
yes, I can access it again. there is an error on running the extended version hugo on older ubuntu installations. unfortunately this can't be fixed by hookay, some system c++ libs have to be updated/reininstalled. :/
I found a config [script file](https://github.com/nikku/hugo-cli/blob/master/.travis.yml) for a test environment that fixes this for ubuntu 16, adapting the before_install section with your ubuntu/libcc version and run it on the server once could help, but also the risk of side effects to other services (really just guessing, I have no experience with it).
[more info](https://discourse.gohugo.io/t/solved-hugo-v44-extended-and-relocation-errors-on-travis/13029/2)

**Comment by lislis** [comment]
Yeah, we're looking into upgrading the ubuntu version today :sigh_cat: Thanks for all your help!
Once this is done I think we're good to go :)
I'm closing the ticket as building sites with Hugo works now!! :tada:
